### PR TITLE
Fix rk tests

### PR DESCRIPTION
**Pull request by antonio-fr**
Option rk is invalid in GetAssertion
All authentications need to be reversed related to credentials registrations
Some checks added

### CODE REVIEW

**Comment by conorpp** [comment]
Thanks for catching this!  Could you please link to the relevant parts in the spec for these changes?

**Comment by antonio-fr** [comment]
**Option rk is invalid in GetAssertion**
[CTAP2 standard GetAssertion](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#authenticatorGetAssertion)
_The following values are defined for use in the options parameter : up, uv.
When an authenticatorGetAssertion request is received, the authenticator performs the following procedure: 5 ... If the option is known but not valid for this command, terminate this procedure and return CTAP2_ERR_INVALID_OPTION._
So in case the rk option is present in the GetAssertion command, the device must return INVALID_OPTION (x2C). A good implementation, and many famous implementations, of this standard are failing on this test because the test sends incorrectly the rk option (as it remains from MakeCredential request).

**All authentications need to be reversed related to credentials registrations**
In the same section of the standard, about GetAssertion : _If more than one credential was located and allowList is present and not empty, select any applicable credential. Otherwise, order the credentials by the time when they were created in reverse order. The first credential is the most recent credential that was created._
Then GetNextAssertion allows to go over all the credentials.
Note that this reversal is done in some tests in test_resident_keys, but not in every tests. For example, here, the credentials are correctly reversed : https://github.com/solokeys/fido2-tests/blob/c5e51022b354bef012506d09a6dff14ae0530eb1/tests/standard/fido2/test_resident_key.py#L96

The **checks added in test_user_info_returned** are just to test many data returned, mainly if the data returned are the same as when they were registered. For now, it only tests if there's a single id key when no PIN (no uv), which is quite thin.

**Comment by conorpp** [comment]
Okay great, thank you for catching this and for the PR!

**Comment by conorpp** [comment]
I'm going to make one change, but want to run by you in case I'm mistaken.

https://github.com/solokeys/fido2-tests/blob/3d93c5c502464ef689b78c01e55959800d4b1ca9/tests/standard/fido2/test_resident_key.py#L56-L57

It should be something more like this?

```python
        if not MC_RK_Res.request.pin_protocol or not GA_RK_Res.number_of_credentials:
            assert "id" in GA_RK_Res.user.keys() and len(GA_RK_Res.user.keys()) == 1
```

> For multiple accounts per RP case, where the authenticator does not have a display, authenticator returns "id" as well as other fields to the platform. Platform will use this information to show the account selection UX to the user and for the user selected account, it will ONLY return "id" back to the [WebAuthn] layer and discard other user details.

**Pull request merged**
