### PR TITLE
Black with prehooks

### PR DESCRIPTION
**Pull request by nickray**
This builds on https://github.com/solokeys/fido2-tests/pull/1.
Not 100% sure about the `precommit` thing, but maybe simpler than catching it in CI.
Does it work on Windows?

### CODE REVIEW

**Comment by conorpp** [comment]
I added details to make it windows compatible.  Python black does not work, it outputs a lot of `A process in the process pool was terminated abruptly while the future was running or pending`, but using black `18.9b0` works fine.

**Comment by nickray** [comment]
Will review tomorrow.

**Comment by nickray** [comment]
I reverted the `--user` in `$(BIN)/pip install --user -U pip` because otherwise you update a different pip to the one you're calling immediately after. Or what's the reasoning? Might this fix your black issue too?

**Comment by conorpp** [comment]
I'm not really sure what is going on, and running in an admin shell doesn't help.  Seems other people have only been able to solve with `--user` which doesn't help venv.
https://github.com/pypa/pip/issues/6068
using `$(BIN)/python -m pip install --upgrade pip` works though.

**Comment by nickray** [comment]
Seems this finally works on both platforms.

**Pull request merged**
